services:
  mongo:
    container_name: mongodb
    image: mongo:8.2.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      # test: [ "CMD", "powershell", "-command", "try { (Test-NetConnection -ComputerName localhost -Port 27017).TcpTestSucceeded } catch { exit 1 }" ]
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand(\"ping\")' localhost:27017 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mongodb_shared_network

volumes:
  mongo_data:


networks:
  mongodb_shared_network:
    name: mongodb_shared_network
    driver: bridge
